<a href="https://colab.research.google.com/github/mahfuz978/TECH-I.S.---DATA-PROCESSING/blob/main/Mahfuzur_Rahman_Manipulating_Data_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# example 1:
lst = [10,200,90,0]

import numpy as np
arr = np.array(lst)

print(arr + 10)

[ 20 210 100  10]


In [2]:
# example 2

lst = [22,45,78,50]

import sys
arr = np.array(lst)
print(arr.itemsize)
print(arr.nbytes)
print(sys.getsizeof(lst))

8
32
96


In [3]:
#array creation
a = np.array([1,2,3,4]) # one dimensional
b = np.array([[1,2],[2,3]]) # two dimensional
print(a)
print("-----")
print(b)

[1 2 3 4]
-----
[[1 2]
 [2 3]]


In [4]:
# shape
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]])

print("The shape of the array a is:", a.shape)
print("The shape of array b is:", b.shape)

The shape of the array a is: (4,)
The shape of array b is: (2, 4)


In [5]:
# dimensions
print('The dimension of array a is:', a.ndim)
print('The dimension of array b is:', b.ndim)

The dimension of array a is: 1
The dimension of array b is: 2


In [6]:
# size
print('the size of array a is:', a.size)
print('the size of array b is:', b.size)

the size of array a is: 4
the size of array b is: 8


In [7]:
# datatype
print('the data type of array a is:', a.dtype)
print('the data type of array b is:', b.dtype)

the data type of array a is: int64
the data type of array b is: int64


In [8]:
# itemsize
print('Array a has:',a.itemsize,"bytes")
print("Array b has:",b.itemsize,"bytes" )

Array a has: 8 bytes
Array b has: 8 bytes


#**Matrix Creation**

In [9]:
print(np.array([5,6,8,45,12,52]).reshape(2,3))

[[ 5  6  8]
 [45 12 52]]


In [10]:
print(np.matrix([[1,2],[2,3]]))

[[1 2]
 [2 3]]


In [11]:
print(np.eye(3)) # identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(np.ones((3,3), dtype = np.float64))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
print(np.arange(1,20, dtype = "int32"))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
print(np.arange (1,20,2, dtype="int8"))

[ 1  3  5  7  9 11 13 15 17 19]


#Practice Exercise:

In [16]:
#1:
"""
Store the marks and IDs of three students as NumPy arrays.
The marks are [20, 30, 40] and IDs are [0,2,4]. 
Store array for marks in a variable marks and the one for 
IDs in another variable ids. Display both marks and ids.
"""

marks = np.array([20,30,40])
ids = np.array([0,2,4])
print(np.vstack([marks, ids]))

[[20 30 40]
 [ 0  2  4]]


In [17]:
#2
"""
Given two NumPy arrays arr1 = [25, 56, 12, 85, 34, 75] and 
arr2 = [42, 3, 86, 32, 856, 46], solve the following:

a. Create a new NumPy array Narr with the shape equal to arr1 filled with 
random values.

b. Permanently change the dtype of arr1 to complex
"""

# 2a.
arr1 = np.array([25, 56, 12, 85, 34, 75])
arr2 = np.array([42, 3, 86, 32, 856, 46])

narr = np.random.rand(arr1.size)
print(narr)


[0.06032758 0.740138   0.43988156 0.98577345 0.33443399 0.84496557]


In [18]:
# 2b.
arr1 = arr1.astype('complex128')
print(arr1)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


In [19]:
print(arr1.dtype)

complex128


#**INDEXING AND SLICING**

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

#  pull out second element of third row
print(a[2][1])
print('----')
# pull out first two rows and columns
print(a[:2, :2])
print('----')
# pull out all the elements of the third row
print(a[2, :])

8
----
[[1 2]
 [4 5]]
----
[7 8 9]


##Integer Array indexing

In [21]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print('----')

print(np.array([a[0,0],a[1,1],a[2,0]]))
print('----')

print(a[[0,0],[1,1]])
print('----')

print(np.array([a[0,1], a[0,1]]))

[1 4 5]
----
[1 4 5]
----
[2 2]
----
[2 2]


In [22]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])

#boolean condition for values greater than 3
mask = a > 3

# masking for the above boolean condition in the array
print(a[mask])

[4 7 5 7 7]


In [23]:
#example

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[arr>2])


[3 4 5 6 7]


In [24]:
# creating two arrays for operations
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [25]:
print(a+b)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [26]:
print(a-b)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [27]:
print(a*b)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [28]:
print(a/b)

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [29]:
# square root transformation
a = np.array([[1,4,9],[16,25,36]])
print(np.sqrt(a))

[[1. 2. 3.]
 [4. 5. 6.]]


In [30]:
# these functions can also be like
'''
np.add(a,b)
np.substract(a,b)
np.multiply(a,b)
np.divide(a,b)
np.sqrt(a)
np.log(a)
'''

'\nnp.add(a,b)\nnp.substract(a,b)\nnp.multiply(a,b)\nnp.divide(a,b)\nnp.sqrt(a)\nnp.log(a)\n'

In [31]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(a))
print(np.log(a))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [32]:
#practice usages can be like:
'''
a.sum() Array-wise sum
a.min() Array-wise minimum value
a.max(axis=0) Maximum value of an array row
a.cumsum(axis=1) Cumulative sum of the elements
a.mean() Mean
np.median(a) Median
np.corrcoef(a) Correlation coefficient
np.std(a) Standard deviation
'''
print(a.sum())
print(a.min())
print(a.max(axis = 0))
print(a.cumsum(axis = 1))
print(a.mean())
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))

45
1
[7 8 9]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
5.0
5.0
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2.581988897471611


In [33]:
# roots of a qudratic equation can be calculated
coefficients = np.array([1,-4,4])
roots = np.roots(coefficients)
print(roots)

[2. 2.]


In [34]:
# array comparison
a = np.array([5,6,7,8])
b = np.array([5,6,7,8])
print(np.array_equal(a,b))

True


In [35]:
# axes notation
a = np.array([[2,5,7],[4,25,30]])

# computes the sum over column
print(np.sum(a, axis=0))

# computes the sum over rows
print(np.sum(a, axis=1))

print(np.sum(a))

[ 6 30 37]
[14 59]
73


#Practice Exercises

In [36]:
'''
We have a buy sell problem:

Initialize an array [[40, 35, 20], [21, 48, 70]] which constitutes the prices
on 2 consecutive day at 3 different sessions of the day. The objective is to
buy at minimum price on day 1 and sell at maximum on day.

1.Find the minimum price on day 1.
2.Find the maximum price on day 2.
3.Calculate the profit and print it.
4.Find the index of the session on which buying and selling took place.
Hint:
Use array.min() and array.max() to find the minimum and maximum prices.
Filter arrays for different days using array[0:] and array[1:]
Index = list(array).index(value)
'''

'\nWe have a buy sell problem:\n\nInitialize an array [[40, 35, 20], [21, 48, 70]] which constitutes the prices\non 2 consecutive day at 3 different sessions of the day. The objective is to\nbuy at minimum price on day 1 and sell at maximum on day.\n\n1.Find the minimum price on day 1.\n2.Find the maximum price on day 2.\n3.Calculate the profit and print it.\n4.Find the index of the session on which buying and selling took place.\nHint:\nUse array.min() and array.max() to find the minimum and maximum prices.\nFilter arrays for different days using array[0:] and array[1:]\nIndex = list(array).index(value)\n'

In [37]:
arr = np.array([[40, 35, 20], [21, 48, 70]])

print('1.',np.min(arr[0]))
print('2.',np.max(arr[1]))
print('3.',np.sum(arr))
index1 = arr[0,0]
index2 = arr[0,1]
index3 = arr[0,2]
index4 = arr[1,0]
index5 = arr[1,1]
index6 = arr[1,2]
print(index1)
print(index2)
print(index3)
print(index4)
print(index5)
print(index6)

1. 20
2. 70
3. 234
40
35
20
21
48
70


In [38]:
# broad casting
np.arange(3)+4

array([4, 5, 6])

In [39]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [40]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#Practice Exercise

In [41]:
'''
1.Create a random 5x5 matrix with the help of np.random.random((5,5))
2.Calculate the minimum and maximum value with the help of .min() and 
.max() methods respectively
3.Now using the power of broadcasting subtract the minimum value from each
 element and divide by their range (maximum-minimum) to normalize. 
 Save this normalized as z_norm
4.Print the standardized array
'''

arr = np.random.random((5,5))
max = np.max(arr)
min = np.min(arr)
range = max - min
def z_norm():
  for i in arr:
    print((i-min)/range)

In [42]:
z_norm()

[0.90331504 0.07666305 0.20335354 0.83098513 0.97026908]
[0.38444675 0.32147075 1.         0.3241772  0.78157976]
[0.29140187 0.61792711 0.36395409 0.76370484 0.3264132 ]
[0.23368466 0.47445274 0.36865205 0.98736173 0.        ]
[0.61769326 0.82517542 0.35333482 0.2294131  0.98260338]


In [43]:
data_file = '/content/sample_data/makeSenseOfCensus.txt'

In [44]:
data = np.genfromtxt(data_file, delimiter=',', skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [45]:
data.shape

(1000, 8)

In [46]:
print('\nDATA: \n\n', type(data))


DATA: 

 <class 'numpy.ndarray'>


In [47]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
np.concatenate((data, new_record))

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [48]:
# Step 3 : Check if it's a young country or old country
'''
Create a new array called 'age' by taking only age column(age is 
the column with index 0) of 'census' array.

Find the max age and store it in a variable called 'max_age'.

Find the min age and store it in a variable called 'min_age'.

Find the mean of the age and store it in a variable called 'age_mean'.

Find the standard deviation of the age and store it in a variable 
called 'age_std'

'''

age = data[:,0]
max_age = np.max(age)
min_age = np.min(age)
avg_age = age.mean()
std_age = np.std(age)
avg_age

38.051

In [49]:
#Step 4: Let's check the country's race distribution to identify the minorities
'''
Create four different arrays by subsetting 'census' array by Race column
(Race is the column with index 2) and save them in 'race_0','race_1', 
'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array 
where 'race'column has value 0 in 'race_0', so on and so forth)

Store the length of the above created arrays in 'len_0', 'len_1','len_2',
 'len_3' and 'len_4' respectively

Find out which is the race with the minimum no. of citizens

Store the number associated with the minority race in a variable called 
'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 
'minority_race' because that is the index of the race having the least
 no. of citizens )
'''
race_0 = data[data[:,2] == 0]
race_1 = data[data[:,2] == 1]
race_2 = data[data[:,2] == 2]
race_3 = data[data[:,2] == 3]
race_4 = data[data[:,2] == 4]

len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

print(len_0)
print(len_1)
print(len_2)
print(len_3)
print(len_4)

10
27
110
6
847


In [50]:
minority_race = race_3

In [51]:
# Step 5: As per govt. records citizens above 60 should not work more than 25
# hours a week. Let us check if the policy is in place

'''
1.Create a new subset array called 'senior_citizens' by filtering 'census' 
according to age>60 (age is the column with index 0)

2.Add all the working hours(working hours is the column with index 6) of 
'senior_citizens' and store it in a variable called 'working_hours_sum'

3.Find the length of 'senior_citizens' and store it in a variable called 
'senior_citizens_len'

4.Finally find the average working hours of the senior citizens by dividing 
'working_hours_sum' by 'senior_citizens_len' and store it in a variable called
 'avg_working hours'.

5.Print 'avg_working_hours' and see if the govt. policy is followed.
'''

senior_citizens = data[:,0]>60
working_hours_sum =sum(data[senior_citizens, 6])
senior_citizens_len = len(data[data[:,0]>60])
avg_working_hours = working_hours_sum/senior_citizens_len
avg_working_hours

31.42622950819672

In [52]:
#Step 6: Let's check that higher educated people have better pay in general.
'''
Create two new subset arrays called 'high' and 'low' by filtering 'census'
 according to education-num>10 and education-num<=10 (education-num is the 
 column with index 1) respectively.

Find the mean of income column(income is the column with index 7) of 'high' 
array and store it in 'avg_pay_high'. Do the same for 'low' array and store 
it's mean in 'avg_pay_low'.
'''
high = data[:,1]>10

low = data[:,1]<=10

avg_pay_high = data[high, 7].mean()
avg_pay_low = data[low, 7].mean()

In [53]:
data_file = '/content/sample_data/KAG_Conversion_Data.txt'

In [54]:
data = np.genfromtxt(data_file, delimiter=',', skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [55]:
# instructions

'''
Load the data. Data is already given to you in variable path

How many unique ad campaigns (xyzcampaignid) does this data contain ? 
And for how many times was each campaign run ?

What are the age groups that were targeted through these ad campaigns?

What was the average, minimum and maximum amount spent on the ads?

What is the id of the ad having the maximum number of clicks ?

How many people bought the product after seeing the ad with most clicks? 
Is that the maximum number of purchases in this dataset?

So the ad with the most clicks didn't fetch the maximum number of purchases. 
Find the details of the product having maximum number of purchases
'''
unique_xyzcampaignid = np.unique(data[:,1])
print("unique_xyzcampaignids:" , unique_xyzcampaignid )
len_916 = len(data[data[:,1]==916.])
print('len_916:',len_916)
len_936 = len(data[data[:,1]==936.])
print('len_936:',len_936)
len_1178 = len(data[data[:,1]==1178.])
print('len_1178:',len_1178)

unique_xyzcampaignids: [ 916.  936. 1178.]
len_916: 54
len_936: 464
len_1178: 625


In [56]:
#What are the age groups that were targeted through these ad campaigns?
# age_groups = np.unique(data[:,3])
# age_groups

In [57]:
# x = data[:[:1],3]

In [58]:
#What was the average, minimum and maximum amount spent on the ads?
money = data[:, 8]
max_spent = np.max(money)
print(max_spent)
min_spent = np.min(money)
print(min_spent)
avg_spent = money.mean()
print(avg_spent)

639.9499981
0.0
51.36065613141295


In [59]:
#What is the id of the ad having the maximum number of clicks ?
clic = data[:,7]
mx_clik = np.max(clic)
print('max_clicked:',mx_clik)
id_loc = list(clic).index(421.0)
id_no = data[id_loc, 0]
print("ID of max clicked ad:",id_no)

max_clicked: 421.0
ID of max clicked ad: 1121814.0


In [60]:
#How many people bought the product after seeing the ad with most clicks? 
#Is that the maximum number of purchases in this dataset?

people_bought = data[id_loc, 10]
print(people_bought, "people bought the product after seeing the ad.")
max_purchases = np.max(data[:,10])
print(max_purchases,"is the maximum purchase in this dataset.")

13.0 people bought the product after seeing the ad.
21.0 is the maximum purchase in this dataset.


In [61]:
#So the ad with the most clicks didn't fetch the maximum number of purchases.
# Find the details of the product having maximum number of purchases

purchases = data[:,10]
# mx_clik = np.max(clic)
id_loc = list(clic).index(21.0)
print('id_location:', id_loc)
details = data[id_loc,:]
print("Details:\n", np.vstack(details))

id_location: 195
Details:
 [[7.48230000e+05]
 [9.36000000e+02]
 [1.11006000e+05]
 [           nan]
 [           nan]
 [1.60000000e+01]
 [8.39290000e+04]
 [2.10000000e+01]
 [2.77299995e+01]
 [4.00000000e+00]
 [1.00000000e+00]]
